// this file is auto-generated by the generate-types script
// do not edit this file directly; to regenerate, run the generate-types script

export interface CoreConfig {
    content: import("../src/config/content.config").ContentConfig;
    cucumber: import("../src/config/cucumber.config").CucumberConfig;
    debug: import("../src/config/debug.config").DebugConfig;
    paths: import("../src/config/paths.config").PathsConfig;
    plugins: import("../src/config/plugins.config").PluginsConfig;
    watch: import("../src/config/watch.config").WatchConfig;
}
