// this file is auto-generated by the generate-types script
// do not edit this file directly; to regenerate, run the generate-types script

export interface RunnerConfig {
    cucumber: import("../config/cucumber.config").CucumberConfig;
    paths: import("../config/paths.config").PathsConfig;
    plugins: import("../config/plugins.config").PluginsConfig;
}
