/**
 * Generates type definitions using the type generation scripts in the
 * `@specify/core/scripts/types` directory.
 *
 * The generated type definitions are written to the `@/types/index.d.ts` file.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";
import { globbySync } from "globby";

import type { InterfaceExportOptions } from "./utils";

const __dirname = import.meta.dirname;
const outputFile = path.join(__dirname, "..", "types", "index.d.ts");

const typeScripts = globbySync([path.join(__dirname, "types", `*.ts`)], {
    "absolute": true,
    "onlyFiles": true,
});

const exports = [] as string[];

for (const scriptPath of typeScripts) {
    const { generateTypeExport } = (await import(scriptPath)) as {
        generateTypeExport: (opts: InterfaceExportOptions) => string;
    };

    // run the type generation script (no need to await)
    exports.push(generateTypeExport({ outputFile }));
}

const outputHeader =
    "// this file is auto-generated by the generate-types script\n" +
    "// do not edit this file directly; to regenerate, run the generate-types script\n\n";

writeFileSync(outputFile, outputHeader + exports.join("\n\n") + "\n");
