// this file is auto-generated by the generate-types script
// do not edit this file directly; to regenerate, run the generate-types script

export interface CoreConfig {
    cucumber: import("../src/config/cucumber.config").CucumberConfig;
    paths: import("../src/config/paths.config").PathsConfig;
    plugins: import("../src/config/plugins.config").PluginsConfig;
}
