// this file is auto-generated by the generate-types script
// do not edit this file directly; to regenerate, run the generate-types script

export interface CoreConfig {
    browsers: import("../config/browsers.config").BrowsersConfig;
    content: import("../config/content.config").ContentConfig;
    cucumber: import("../config/cucumber.config").CucumberConfig;
    debug: import("../config/debug.config").DebugConfig;
    paths: import("../config/paths.config").PathsConfig;
    plugins: import("../config/plugins.config").PluginsConfig;
    time: import("../config/time.config").TimeConfig;
    watch: import("../config/watch.config").WatchConfig;
}
