/**
 * Step Definition Documentation Generator
 *
 * Parses step definition source files in the current package and generates
 * a Markdown reference document for each module, extracting step patterns
 * and handler JSDoc comments.
 *
 * Invoke from the root directory of the package to document:
 *   tsx ../../scripts/generate-step-docs.ts
 */

import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path                                 from "node:path";

import { globbySync                } from "globby";
import { Node, Project, SyntaxKind } from "ts-morph";

import type { JSDoc, JSDocTag, StringLiteral } from "ts-morph";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ModuleDoc {
    name: string;
    description: string;
}

interface ParsedJSDoc {
    title: string;
    description: string;
    remarks: string;
    params: string[];
    throws: Array<{ type: string; description: string }>;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const packageRoot = process.cwd();

const stepDefPaths = globbySync("src/cucumber/step_definitions/**/*.ts", {
    "cwd":      packageRoot,
    "absolute": true,
});

if (stepDefPaths.length === 0) {
    process.exit(0);
}

const outputDir = path.join(packageRoot, "docs", "markdown", "cucumber", "step_definitions");

// Clear the output directory so stale docs from deleted or renamed modules
// don't accumulate. Everything under this path is generated by this script.
rmSync(outputDir, { "recursive": true, "force": true });
mkdirSync(outputDir, { "recursive": true });

const project = new Project({ "skipAddingFilesFromTsConfig": true });

for (const filePath of stepDefPaths) {
    const sourceFile = project.addSourceFileAtPath(filePath);
    const fileName   = path.basename(filePath, ".ts");
    const moduleDoc  = parseModuleDoc(sourceFile.getFullText());

    // Find every defineStep(...) call in the file
    const defineStepCalls = sourceFile
        .getDescendantsOfKind(SyntaxKind.CallExpression)
        .filter((call) => {
            const expr = call.getExpression();
            return Node.isIdentifier(expr) && expr.getText() === "defineStep";
        });

    const sections: string[] = [];

    for (const call of defineStepCalls) {
        const args = call.getArguments();

        // Extract step patterns from the first argument.
        // If the arg is missing or not a string/array, skip this call gracefully.
        const firstArg         = args[0];
        let patterns: string[] = [];

        if (Node.isStringLiteral(firstArg)) {
            patterns = [firstArg.getLiteralValue()];
        } else if (Node.isArrayLiteralExpression(firstArg)) {
            patterns = firstArg
                .getElements()
                .filter((el): el is StringLiteral => Node.isStringLiteral(el))
                .map((el) => el.getLiteralValue());
        }

        if (patterns.length === 0) {
            continue;
        }

        // Extract handler name from the second argument.
        // If the arg is missing or not an identifier, skip this call gracefully.
        const secondArg = args[1];

        if (!Node.isIdentifier(secondArg)) {
            continue;
        }

        const handlerName = secondArg.getText();

        // Look up the handler function and parse its JSDoc.
        const fn     = sourceFile.getFunction(handlerName);
        const jsDocs = fn?.getJsDocs() ?? [];
        const parsed = jsDocs.length > 0 ? parseJSDoc(jsDocs[0]) : null;

        const heading = parsed?.title ? parsed.title : `\`${handlerName}\``;

        sections.push(buildSection(heading, patterns, parsed));
    }

    if (sections.length === 0) {
        continue;
    }

    // Compose and write the Markdown document.
    let doc = `# ${moduleDoc.name}\n\n`;

    if (moduleDoc.description) {
        doc += `${moduleDoc.description}\n\n`;
    }

    doc += sections.join("\n---\n\n");

    writeFileSync(path.join(outputDir, `${fileName}.md`), doc);

    // eslint-disable-next-line no-console
    console.log(`  Generated: docs/markdown/cucumber/step_definitions/${fileName}.md`);
}

// ---------------------------------------------------------------------------
// Parsers
// ---------------------------------------------------------------------------

/**
 * Extract the module name and description from the first JSDoc block in the
 * source text.  The first non-empty line of the comment body is treated as
 * the module name; the remaining lines form the description.
 */
function parseModuleDoc(sourceText: string): ModuleDoc {
    const match = sourceText.match(/^\/\*\*([\s\S]*?)\*\//);

    if (!match) {
        return { "name": "Step Definitions", "description": "" };
    }

    const lines = stripJSDocDecorations(match[0]);

    const nameIdx = lines.findIndex((l) => l.trim() !== "");
    const name    = nameIdx >= 0 ? lines[nameIdx].trim() : "Step Definitions";

    const description = lines
        .slice(nameIdx + 1)
        .join(" ")
        .trim()
        .replace(/\s+/g, " ");

    return { name, description };
}

/**
 * Parse a handler function's JSDoc comment into structured fields.
 *
 * The first paragraph of the comment body (before the first blank line) is
 * treated as the title. Any remaining prose before the first `@` tag becomes
 * the description.
 */
function parseJSDoc(jsDoc: JSDoc): ParsedJSDoc {
    const lines = stripJSDocDecorations(jsDoc.getText());

    const result: ParsedJSDoc = {
        "title":       "",
        "description": "",
        "remarks":     "",
        "params":      [],
        "throws":      [],
    };

    // Split the raw lines into a preamble (prose before the first @tag) to
    // extract the title and description. Tags are handled via the structured API.
    const tagStart = lines.findIndex((l) => l.startsWith("@"));
    const preamble = tagStart >= 0 ? lines.slice(0, tagStart) : lines;

    // Strip leading blank lines, split the preamble into paragraphs, then
    // search for a sentence boundary (". ") within the first paragraph only:
    //   - Found: title = before the period; description = rest of that
    //     paragraph joined with any further paragraphs.
    //   - Not found: entire first paragraph is the title; remaining
    //     paragraphs become the description.
    const contentStart = preamble.findIndex((l) => l.trim() !== "");
    const trimmed      = contentStart >= 0 ? preamble.slice(contentStart) : [];

    const paragraphs: string[] = [];
    let paraBuffer: string[]   = [];

    for (const line of trimmed) {
        if (line.trim() === "") {
            if (paraBuffer.length > 0) {
                paragraphs.push(paraBuffer.join(" ").replace(/\s+/g, " ").trim());
                paraBuffer = [];
            }
        } else {
            paraBuffer.push(line);
        }
    }
    if (paraBuffer.length > 0) {
        paragraphs.push(paraBuffer.join(" ").replace(/\s+/g, " ").trim());
    }

    const firstPara     = paragraphs[0] ?? "";
    const restParas     = paragraphs.slice(1).join(" ").trim();
    const sentenceBreak = firstPara.indexOf(". ");

    if (sentenceBreak >= 0) {
        result.title = firstPara.slice(0, sentenceBreak);
        const restOfFirst = firstPara.slice(sentenceBreak + 2).trim();
        result.description = [restOfFirst, restParas].filter(Boolean).join(" ");
    } else {
        result.title = firstPara.replace(/\.$/, "").trim();
        result.description = restParas;
    }

    // Use ts-morph's structured tag API for @param, @throws, and @remarks.
    // @throws requires standard {Type} notation; entries without braces are
    // silently skipped until docblocks are updated (see ticket #331).
    for (const tag of jsDoc.getTags()) {
        const comment = tagCommentToString(tag.getComment());

        if (Node.isJSDocParameterTag(tag)) {
            // getComment() returns the description without the parameter name;
            // strip a leading dash that may remain from "name - description" format.
            result.params.push(comment.replace(/^[-–]\s*/, ""));
        } else if (Node.isJSDocThrowsTag(tag)) {
            const type = tag.getTypeExpression()?.getTypeNode().getText();
            if (type) {
                result.throws.push({ type, "description": comment });
            }
        } else if (tag.getTagName() === "remarks") {
            result.remarks = comment;
        }
    }

    return result;
}

/**
 * Normalise a JSDocTag comment value — which ts-morph returns as a string,
 * an array of inline nodes, or undefined — to a plain single-line string.
 * Internal whitespace (including newlines from wrapped comment text) is
 * collapsed so that multi-line tag values render correctly in Markdown.
 */
function tagCommentToString(raw: ReturnType<JSDocTag["getComment"]>): string {
    if (!raw) return "";
    const text = typeof raw === "string" ? raw : raw.map((part) => part.getText()).join("");
    return text.replace(/\s+/g, " ").trim();
}

/**
 * Remove `/** * /` delimiters and leading `*` characters from each line of a
 * JSDoc block, returning the cleaned lines.
 */
function stripJSDocDecorations(raw: string): string[] {
    return raw
        .replace(/^\/\*\*/, "")
        .replace(/\s*\*\/$/, "")
        .split("\n")
        .map((line) => line.replace(/^\s*\*\s?/, "").trimEnd());
}

// ---------------------------------------------------------------------------
// Markdown builders
// ---------------------------------------------------------------------------

/**
 * Compose the Markdown section for a single step definition.
 */
function buildSection(heading: string, patterns: string[], doc: ParsedJSDoc | null): string {
    const lines: string[] = [];

    lines.push(`## ${heading}`, "");
    lines.push(...patterns.map((p) => `- \`${p}\``), "");

    if (doc?.description) {
        lines.push(doc.description, "");
    }

    if (doc?.remarks) {
        lines.push(`> ${doc.remarks}`, "");
    }

    if (doc?.params.length) {
        lines.push("**Parameters**", "");
        lines.push("| # | Description |");
        lines.push("|---|-------------|");
        doc.params.forEach((desc, i) => lines.push(`| ${i + 1} | ${desc} |`));
        lines.push("");
    }

    if (doc?.throws.length) {
        lines.push("**Throws**", "");
        doc.throws.forEach(({ type, description }) => {
            lines.push(`- \`${type}\`${description ? ` — ${description}` : ""}`);
        });
        lines.push("");
    }

    return lines.join("\n");
}
