name: Release Stage 6 - Validate
on:
  workflow_call:
    inputs:
      git_tag:
        description: "The Git tag produced by stage 1"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      git_tag:
        description: "The Git tag produced by stage 1"
        required: true
        type: string
permissions:
  contents: read
concurrency:
  group: release-stages
jobs:
  validate:
    name: Validate published package
    runs-on: ubuntu-${{ vars.UBUNTU_VERSION }}
    env:
      GIT_BRANCH: main
    steps:
      # - name: Check out source repository code
      #   uses: actions/checkout@v6
      #   with:
      #     path: ./source
      #     ref: ${{ env.GIT_BRANCH }}
      - name: Check out validate repository code
        uses: actions/checkout@v6
        with:
          # path: ./validate
          ref: ${{ env.GIT_BRANCH }}
          repository: specify-bdd/validate
          submodules: true
      - name: Setup Node.js ${{ vars.NODE_LTS_ACTIVE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_LTS_ACTIVE_VERSION }}
      - name: Install latest package versions
        run: npm run update-specify -- ${{ inputs.git_tag }}
        # working-directory: ./validate
      - name: Run test suite
        run: npx specify test specify/features
        # working-directory: ./validate
